INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIPAM','Developpement dapplications dans un environnement oracle','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIPAM','Analyse de systemes dinformation I','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIPAM','Developpement Web avance avec JavaScript et HTML5','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIPAM','Programmation Orientee Objet','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIPAM','Programmation dapplications de donnees multicouches sous .NET','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIPAM','Introduction aux affaires','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIPAM','Analyse des systemes dinformation II','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIPAM','Programmation ADO.NET','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIPAM','Programmation ASP.NET','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIPAM','Redaction Professionnelle I','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIPAM','Programmation Java et développement dapplications mobile sous Android','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIPAM','Programmation web côte serveur avec les logiciels libres','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIPAM','Developpement Applications Multiplateformes','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIPAM','Programmation Web PHP et Ajax','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIPAM','Projet de Developpement Applications Informatiques','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIPAM','Certification MCSA SQL Server','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIPAM','TP Certification Dabase Fundamentals','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIPAM','Travail Securitaire','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIPAM','Programmation XML et services Web','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIPAM','Introduction à la gestion des projets','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(001,'TIPAM','Conception de Bases de Données Relationnelles','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(001,'TIPAM','Programmation Windows Forms Sous .Net','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(001,'TIPAM','Programmation Structurée II','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(001,'TIPAM','Structures de Données et Algorithmes','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(001,'TIPAM','Programmation Windows Forms Avancée Sous .Net','RAS');
-
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIRSI','TP CISCO CCNA Module 2-3-4','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIRSI','Sécurité des Réseaux ','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIRSI','Outils de réseautique','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIRSI','Service dannuaire','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIRSI','CCNA-Routage et Commutation avancés','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIRSI','Téléphonie IP','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIRSI','Développement Personnel et Ethique','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIRSI','Infrastructure Virtuelle','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIRSI','Réseaux Microsoft II','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIRSI','CCNA-Routage et Commutation','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(001,'TIRSI','A+ III - Solutions Mobiles et  Impression','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(001,'TIRSI','Sécurité Informatique','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIRSI','Linux et Infrastructres','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIRSI','Redaction Professionnelle I','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIRSI','Introduction aux affaires','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIRSI','Introduction à la gestion des projets','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(002,'TIRSI','Travail Securitaire','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(001,'TIRSI','A+ II - Configuration de Matériel Informatique','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(001,'TIRSI','A+ II - Réseaux Microsoft I','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(001,'TIRSI','A+ II - CCNA - Concepts de Réseau','RAS');

INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(001,'TIRSI','English second language-Level ','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(001,'TIRSI','Rédaction Technique','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(001,'TIRSI','Système dexploitation','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(001,'TIRSI','Micro-Informatique et Nouvelles Technologies','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(001,'TIRSI','Système de Gestion de Base de Données','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(001,'TIRSI','Programmation XHTML et CSS','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(001,'TIRSI','Economie','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(001,'TIRSI','Comptabilité','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(001,'TIRSI','Programmation structurée I','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(001,'TIRSI','Introduction au système dexploitation Linux','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(001,'TIRSI','Droit de linformatique','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(001,'TIRSI','Mathématiques appliquées à linformatique','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(001,'TIRSI','Introduction aux réseaux','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(001,'TIRSI','Infographie 2D','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(001,'TIRSI','English second language-Level B1.1','RAS');
INSERT INTO Coursdeclasse(classNiveauidNiveau,classSpecialiteNomspec,crsCodeCours,crsSyllabus)VALUES(001,'TIRSI','Introduction à la certification CISCO -CCNA Module 1','RAS');
